webapp:
  platform:
    name: "Test Application"
    version: "1.0.0"
    base_uri: "http://127.0.0.1:8888/"
    tokens:
      public: "1234"      
    database:
      host: "db"
      user: "mariadb"
      password: "mariadb"
      name: "mariadb"
  